# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - analysis
#  - deploy

build:
  stage: build
  image: 
    name: fcf
    entrypoint: [""]
  tags:
    - fcf
    - ssh
  allow_failure: false
  script:
    - echo "setup current branch..."
    - cd /home/hadoop/fast-configuration-fuzzing
    - git checkout tmp
    - git fetch origin $CI_COMMIT_BRANCH
    - git checkout -B $CI_COMMIT_BRANCH origin/$CI_COMMIT_BRANCH

test:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  variables:
    GIT_STRATEGY: none
  image:
    name: fcf
    entrypoint: [""]
  tags:
    - fcf
    - ssh
  allow_failure: true
  before_script:
    - cd /home/hadoop/fast-configuration-fuzzing/test
    - echo "Running unit tests... This will take about 3 minutes."
  script:
    - python3 performAllTests.py
  after_script:
    - cp -rf /home/hadoop/fast-configuration-fuzzing/test /home/hadoop/${CI_PROJECT_DIR}/test
  artifacts:
    paths:
      - test/*/*.log


coverage:
  stage: analysis
  image:
    name: fcf
    entrypoint: [ "" ]
  tags:
    - fcf
    - ssh
  allow_failure: true
  before_script:
    - cd /home/hadoop/fast-configuration-fuzzing/test
    - echo "Running coverage analysis... This will take about 3 minutes."
  script:
    - python3 measureCoverage.py
  after_script:
    - cp -rf /home/hadoop/fast-configuration-fuzzing/test/coverage-html /home/hadoop/${CI_PROJECT_DIR}/test/
    - cp -f /home/hadoop/fast-configuration-fuzzing/test/coverage.txt /home/hadoop/${CI_PROJECT_DIR}/test/
    - cp -f /home/hadoop/fast-configuration-fuzzing/test/coverage.log /home/hadoop/${CI_PROJECT_DIR}/test/
  artifacts:
    paths:
      - test/coverage-html/
      - test/coverage.log
      - test/coverage.txt

#deploy:
#  stage: deploy    # It only starts when the job in the build stage completes successfully.
#  variables:
#    GIT_STRATEGY: none
#  image:
#    name: fcf
#    entrypoint: [ "" ]
#  tags:
#    - fcf
#    - ssh
#  allow_failure: true
#  before_script:
#    - cd /home/hadoop/fast-configuration-fuzzing/src
#    - echo "Testing fuzzer... This will take about 5-10 minutes."
#  script:
#    - python3 fuzzer.py
#  after_script:
#    - cp -rf /home/hadoop/fast-configuration-fuzzing/data/fuzzer/fuzzer.log /home/hadoop/${CI_PROJECT_DIR}/data/fuzzer/
#  artifacts:
#    paths:
#      - data/fuzzer/fuzzer.log

#callgraph:
#  stage: analysis
#  image:
#    name: fcf
#    entrypoint: [ "" ]
#  tags:
#    - fcf
#    - ssh
#  allow_failure: true
#  script:
#    - echo "store build directory..."
#    - export BUILD_DIR=`pwd`
#    - echo $BUILD_DIR
#    - cd /home/hadoop/fast-configuration-fuzzing/test
#    - echo "Running call graph analysis... This will take about 3 minutes."
#    - python3 generateCallGraphs.py
#    - cp -rf /home/hadoop/fast-configuration-fuzzing/test ${BUILD_DIR}/test
#  artifacts:
#    paths:
#      - test/*/*.png
#      - test/callGraph.log